# Generated by Django 4.0.1 on 2022-08-11 18:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('dni', models.CharField(help_text='Número de Identificación', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Identificación')),
                ('name', models.CharField(help_text='Nombre o Razón Social', max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, help_text='Apellido o Nombre Comercial', max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('birth', models.DateField(blank=True, help_text='Fecha de Cumpleaños', null=True, verbose_name='Natalicio')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('photo', models.ImageField(blank=True, help_text='Foto o Imagen en formato png', max_length=255, null=True, upload_to='img', verbose_name='Imagen')),
                ('comment', models.TextField(blank=True, default=None, help_text='Información Adicional', null=True, verbose_name='Observaciones')),
                ('term', models.IntegerField(default=0, help_text='Plazo de Crédito en dias', verbose_name='Plazo')),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de Descuento', max_digits=5, verbose_name='Descuento')),
                ('commision', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de Comisión', max_digits=5, null=True, verbose_name='Comisión')),
                ('collecter', models.BooleanField(help_text='Si es cobrador también', verbose_name='Cobrador')),
                ('genre', models.ForeignKey(help_text='Tipo o Género', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='base.genre', verbose_name='Género')),
            ],
            options={
                'verbose_name': 'Vendedor',
                'verbose_name_plural': 'Vendedores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalVendor',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('dni', models.CharField(db_index=True, help_text='Número de Identificación', max_length=13, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Identificación')),
                ('name', models.CharField(help_text='Nombre o Razón Social', max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, help_text='Apellido o Nombre Comercial', max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('birth', models.DateField(blank=True, help_text='Fecha de Cumpleaños', null=True, verbose_name='Natalicio')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('photo', models.TextField(blank=True, help_text='Foto o Imagen en formato png', max_length=255, null=True, verbose_name='Imagen')),
                ('comment', models.TextField(blank=True, default=None, help_text='Información Adicional', null=True, verbose_name='Observaciones')),
                ('term', models.IntegerField(default=0, help_text='Plazo de Crédito en dias', verbose_name='Plazo')),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de Descuento', max_digits=5, verbose_name='Descuento')),
                ('commision', models.DecimalField(blank=True, decimal_places=2, help_text='Porcentaje de Comisión', max_digits=5, null=True, verbose_name='Comisión')),
                ('collecter', models.BooleanField(help_text='Si es cobrador también', verbose_name='Cobrador')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('genre', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo o Género', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.genre', verbose_name='Género')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Vendedor',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClient',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('dni', models.CharField(db_index=True, help_text='Número de Identificación', max_length=13, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Identificación')),
                ('name', models.CharField(help_text='Nombre o Razón Social', max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, help_text='Apellido o Nombre Comercial', max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('birth', models.DateField(blank=True, help_text='Fecha de Cumpleaños', null=True, verbose_name='Natalicio')),
                ('email', models.EmailField(db_index=True, max_length=255, verbose_name='Correo Electrónico')),
                ('photo', models.TextField(blank=True, help_text='Foto o Imagen en formato png', max_length=255, null=True, verbose_name='Imagen')),
                ('comment', models.TextField(blank=True, default=None, help_text='Información Adicional', null=True, verbose_name='Observaciones')),
                ('term', models.IntegerField(default=0, help_text='Plazo de Crédito en dias', verbose_name='Plazo')),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de Descuento', max_digits=5, verbose_name='Descuento')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('genre', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo o Género', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='base.genre', verbose_name='Género')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, db_constraint=False, help_text='Seleccione un vendedor', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='sales.vendor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'historical Cliente',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('dni', models.CharField(help_text='Número de Identificación', max_length=13, unique=True, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Identificación')),
                ('name', models.CharField(help_text='Nombre o Razón Social', max_length=100, verbose_name='Nombre')),
                ('lastname', models.CharField(blank=True, help_text='Apellido o Nombre Comercial', max_length=100, null=True, verbose_name='Segundo Nombre')),
                ('birth', models.DateField(blank=True, help_text='Fecha de Cumpleaños', null=True, verbose_name='Natalicio')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Correo Electrónico')),
                ('photo', models.ImageField(blank=True, help_text='Foto o Imagen en formato png', max_length=255, null=True, upload_to='img', verbose_name='Imagen')),
                ('comment', models.TextField(blank=True, default=None, help_text='Información Adicional', null=True, verbose_name='Observaciones')),
                ('term', models.IntegerField(default=0, help_text='Plazo de Crédito en dias', verbose_name='Plazo')),
                ('percent_discount', models.DecimalField(decimal_places=2, default=0, help_text='Porcentaje de Descuento', max_digits=5, verbose_name='Descuento')),
                ('genre', models.ForeignKey(help_text='Tipo o Género', on_delete=django.db.models.deletion.RESTRICT, related_name='+', to='base.genre', verbose_name='Género')),
                ('vendor', models.ForeignKey(help_text='Seleccione un vendedor', on_delete=django.db.models.deletion.RESTRICT, to='sales.vendor', verbose_name='Vendedor')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['name'],
            },
        ),
    ]
