# Generated by Django 4.0.1 on 2022-08-11 18:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('manage', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassDocs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('name', models.CharField(help_text='Descripción', max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, help_text='Código Único', max_length=50, null=True, unique=True, verbose_name='Código')),
                ('sri', models.BooleanField(help_text='Si es un documento para el SRI', verbose_name='SRI')),
            ],
            options={
                'verbose_name': 'Tipo Documento',
                'verbose_name_plural': 'Tipos Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='HistoricalDocs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('name', models.CharField(db_index=True, help_text='Descripción', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Código Único', max_length=50, null=True, verbose_name='Código')),
                ('pathdoc', models.CharField(blank=True, help_text='Ruta donde se guarda el archivo', max_length=255, null=True, verbose_name='Ruta')),
                ('receiverdoc', models.CharField(blank=True, help_text='Persona que recibe el documento', max_length=100, null=True, verbose_name='Destinatario')),
                ('xmldoc', models.TextField(blank=True, help_text='Documento Xml', max_length=255, null=True, verbose_name='Xml')),
                ('pdfdoc', models.TextField(blank=True, help_text='Documento Pdf', max_length=255, null=True, verbose_name='Pdf')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classdoc', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de Documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docs.classdocs', verbose_name='TipoDoc')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Documento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalClassDocs',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('name', models.CharField(db_index=True, help_text='Descripción', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Código Único', max_length=50, null=True, verbose_name='Código')),
                ('sri', models.BooleanField(help_text='Si es un documento para el SRI', verbose_name='SRI')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Tipo Documento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='HistoricalAgreements',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(blank=True, editable=False, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('name', models.CharField(db_index=True, help_text='Descripción', max_length=100, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, db_index=True, help_text='Código Único', max_length=50, null=True, verbose_name='Código')),
                ('contact', models.CharField(blank=True, help_text='Contacto de la Empresa', max_length=100, null=True, verbose_name='Contacto')),
                ('chargcontac', models.CharField(blank=True, help_text='Cargo del Contacto', max_length=50, null=True, verbose_name='Cargo')),
                ('start', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de Inicio del Contrato', verbose_name='Inicio')),
                ('end', models.DateTimeField(help_text='Fecha de Finalización del Contrato', verbose_name='Finalizacion')),
                ('comment', models.CharField(blank=True, help_text='Comentarios del Acuerdo', max_length=255, null=True, verbose_name='Comentarios')),
                ('monthly', models.BooleanField(help_text='Si es un valor mensual', verbose_name='Mensual')),
                ('valueunit', models.DecimalField(decimal_places=2, help_text='Acuerdo de Valor de servicio', max_digits=10, verbose_name='Valor Unitario')),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('classdoc', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de Documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='docs.classdocs', verbose_name='TipoDoc')),
                ('company', models.ForeignKey(blank=True, db_constraint=False, help_text='Empresa que tiene el servicio', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manage.company', verbose_name='Empresa')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('module', models.ForeignKey(blank=True, db_constraint=False, help_text='Modulo disponible en el Acuerdo', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='manage.modules', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': 'historical Acuerdo',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
        migrations.CreateModel(
            name='Docs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('name', models.CharField(help_text='Descripción', max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, help_text='Código Único', max_length=50, null=True, unique=True, verbose_name='Código')),
                ('pathdoc', models.CharField(blank=True, help_text='Ruta donde se guarda el archivo', max_length=255, null=True, verbose_name='Ruta')),
                ('receiverdoc', models.CharField(blank=True, help_text='Persona que recibe el documento', max_length=100, null=True, verbose_name='Destinatario')),
                ('xmldoc', models.ImageField(blank=True, help_text='Documento Xml', max_length=255, null=True, upload_to='XML/', verbose_name='Xml')),
                ('pdfdoc', models.ImageField(blank=True, help_text='Documento Pdf', max_length=255, null=True, upload_to='PDF/', verbose_name='Pdf')),
                ('classdoc', models.ForeignKey(help_text='Tipo de Documento', on_delete=django.db.models.deletion.RESTRICT, to='docs.classdocs', verbose_name='TipoDoc')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Agreements',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=1, verbose_name='Activo')),
                ('created', models.DateTimeField(auto_now_add=True, help_text='Fecha de Creación', verbose_name='Creado')),
                ('updated', models.DateTimeField(auto_now=True, help_text='Fecha de Modificación', verbose_name='Modificado')),
                ('name', models.CharField(help_text='Descripción', max_length=100, unique=True, verbose_name='Nombre')),
                ('code', models.CharField(blank=True, help_text='Código Único', max_length=50, null=True, unique=True, verbose_name='Código')),
                ('contact', models.CharField(blank=True, help_text='Contacto de la Empresa', max_length=100, null=True, verbose_name='Contacto')),
                ('chargcontac', models.CharField(blank=True, help_text='Cargo del Contacto', max_length=50, null=True, verbose_name='Cargo')),
                ('start', models.DateTimeField(default=datetime.datetime.now, help_text='Fecha de Inicio del Contrato', verbose_name='Inicio')),
                ('end', models.DateTimeField(help_text='Fecha de Finalización del Contrato', verbose_name='Finalizacion')),
                ('comment', models.CharField(blank=True, help_text='Comentarios del Acuerdo', max_length=255, null=True, verbose_name='Comentarios')),
                ('monthly', models.BooleanField(help_text='Si es un valor mensual', verbose_name='Mensual')),
                ('valueunit', models.DecimalField(decimal_places=2, help_text='Acuerdo de Valor de servicio', max_digits=10, verbose_name='Valor Unitario')),
                ('classdoc', models.ForeignKey(help_text='Tipo de Documento', on_delete=django.db.models.deletion.RESTRICT, to='docs.classdocs', verbose_name='TipoDoc')),
                ('company', models.ForeignKey(help_text='Empresa que tiene el servicio', on_delete=django.db.models.deletion.RESTRICT, to='manage.company', verbose_name='Empresa')),
                ('module', models.ForeignKey(help_text='Modulo disponible en el Acuerdo', on_delete=django.db.models.deletion.RESTRICT, to='manage.modules', verbose_name='Modulo')),
            ],
            options={
                'verbose_name': 'Acuerdo',
                'verbose_name_plural': 'Acuerdos',
                'ordering': ['name'],
            },
        ),
    ]
