# Generated by Django 4.0.1 on 2022-08-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='docs',
            name='access',
            field=models.CharField(blank=True, help_text='Clave de Acceso para el SRI', max_length=49, null=True, verbose_name='Acceso'),
        ),
        migrations.AddField(
            model_name='docs',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Numeración del Documento', null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='docs',
            name='ruc',
            field=models.CharField(blank=True, help_text='Ruc del receptor del Documento', max_length=13, null=True, verbose_name='Ruc'),
        ),
        migrations.AddField(
            model_name='docs',
            name='serie',
            field=models.CharField(blank=True, help_text='Serie del documento para el SRI', max_length=7, null=True, verbose_name='Serie'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='access',
            field=models.CharField(blank=True, help_text='Clave de Acceso para el SRI', max_length=49, null=True, verbose_name='Acceso'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='number',
            field=models.PositiveIntegerField(blank=True, help_text='Numeración del Documento', null=True, verbose_name='Número'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='ruc',
            field=models.CharField(blank=True, help_text='Ruc del receptor del Documento', max_length=13, null=True, verbose_name='Ruc'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='serie',
            field=models.CharField(blank=True, help_text='Serie del documento para el SRI', max_length=7, null=True, verbose_name='Serie'),
        ),
    ]
