# Generated by Django 4.0.1 on 2022-08-11 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0002_docs_access_docs_number_docs_ruc_docs_serie_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='docs',
            name='pdfdoc',
            field=models.FileField(blank=True, help_text='Documento Pdf', max_length=255, null=True, upload_to='PDF/', verbose_name='Pdf'),
        ),
        migrations.AlterField(
            model_name='docs',
            name='xmldoc',
            field=models.FileField(blank=True, help_text='Documento Xml', max_length=255, null=True, upload_to='XML/', verbose_name='Xml'),
        ),
    ]
