# Generated by Django 4.0.1 on 2022-08-16 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0003_alter_docs_pdfdoc_alter_docs_xmldoc'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agreements',
            options={'ordering': ['name'], 'verbose_name': 'Cláusula', 'verbose_name_plural': 'Cláusulas'},
        ),
        migrations.AlterModelOptions(
            name='historicalagreements',
            options={'get_latest_by': 'history_date', 'ordering': ('-history_date', '-history_id'), 'verbose_name': 'historical Cláusula'},
        ),
        migrations.RenameField(
            model_name='docs',
            old_name='ruc',
            new_name='rucdoc',
        ),
        migrations.RenameField(
            model_name='historicaldocs',
            old_name='ruc',
            new_name='rucdoc',
        ),
        migrations.AlterField(
            model_name='agreements',
            name='contact',
            field=models.CharField(blank=True, help_text='Persona de Contacto', max_length=100, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='agreements',
            name='valueunit',
            field=models.DecimalField(decimal_places=2, help_text='Valor de servicio', max_digits=10, verbose_name='Valor Unitario'),
        ),
        migrations.AlterField(
            model_name='historicalagreements',
            name='contact',
            field=models.CharField(blank=True, help_text='Persona de Contacto', max_length=100, null=True, verbose_name='Contacto'),
        ),
        migrations.AlterField(
            model_name='historicalagreements',
            name='valueunit',
            field=models.DecimalField(decimal_places=2, help_text='Valor de servicio', max_digits=10, verbose_name='Valor Unitario'),
        ),
    ]
