# Generated by Django 4.0.1 on 2022-08-26 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('docs', '0004_alter_agreements_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='docs',
            name='pathdoc',
        ),
        migrations.RemoveField(
            model_name='historicaldocs',
            name='pathdoc',
        ),
        migrations.AddField(
            model_name='docs',
            name='datedoc',
            field=models.DateField(blank=True, help_text='Fecha del documento', null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='docs',
            name='pathpdfdoc',
            field=models.CharField(blank=True, help_text='Ruta donde se guarda el archivo 2', max_length=255, null=True, verbose_name='Ruta 2'),
        ),
        migrations.AddField(
            model_name='docs',
            name='pathxmldoc',
            field=models.CharField(blank=True, help_text='Ruta donde se guarda el archivo 1', max_length=255, null=True, verbose_name='Ruta 1'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='datedoc',
            field=models.DateField(blank=True, help_text='Fecha del documento', null=True, verbose_name='Fecha'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='pathpdfdoc',
            field=models.CharField(blank=True, help_text='Ruta donde se guarda el archivo 2', max_length=255, null=True, verbose_name='Ruta 2'),
        ),
        migrations.AddField(
            model_name='historicaldocs',
            name='pathxmldoc',
            field=models.CharField(blank=True, help_text='Ruta donde se guarda el archivo 1', max_length=255, null=True, verbose_name='Ruta 1'),
        ),
    ]
