# Generated by Django 4.0.1 on 2022-08-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schoolfees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicallevel',
            name='code',
            field=models.CharField(blank=True, help_text='Código', max_length=50, null=True, verbose_name='Código'),
        ),
        migrations.AlterField(
            model_name='level',
            name='code',
            field=models.CharField(blank=True, help_text='Código', max_length=50, null=True, verbose_name='Código'),
        ),
    ]
