# Generated by Django 4.0.1 on 2022-01-05 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('schoolfees', '0002_historicalstudent_addreess_historicalstudent_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='historicalstudent',
            old_name='addreess',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='addreess',
            new_name='address',
        ),
    ]
