# Generated by Django 4.0.1 on 2022-01-04 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0002_genre_historicalgenre'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Genre',
        ),
        migrations.DeleteModel(
            name='HistoricalGenre',
        ),
    ]
