# Generated by Django 4.0.1 on 2022-01-05 02:02

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manage', '0003_delete_genre_delete_historicalgenre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='accountantdni',
            field=models.CharField(help_text='Ruc del Contador', max_length=13, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Dni Contador'),
        ),
        migrations.AlterField(
            model_name='company',
            name='agentdni',
            field=models.CharField(help_text='Cédula del Representante Legal', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Dni Representante'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='accountantdni',
            field=models.CharField(help_text='Ruc del Contador', max_length=13, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Dni Contador'),
        ),
        migrations.AlterField(
            model_name='historicalcompany',
            name='agentdni',
            field=models.CharField(help_text='Cédula del Representante Legal', max_length=10, validators=[django.core.validators.RegexValidator('^[A-Za-z0-9]{10,13}', 'Letras o números solamente')], verbose_name='Dni Representante'),
        ),
    ]
